version: '3.8'

services:
  nats-streaming:
    image: nats-streaming:latest
    container_name: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
    command: 
      - "-p"
      - "4222"
      - "-m"
      - "8222"
      - "-cid"
      - "test-cluster"
    restart: unless-stopped